### ISSUE TITLE
Module account_invoice_overdue_reminder V16 not translatable?

### ISSUE THREAD

**Issue by astirpe** [OCA/credit-control#308]
Looks like translation of account_invoice_overdue_reminder is locked in Weblate.

@SirTakobi do you know why is that? We would like to translate it to Dutch...

**Comment by SirTakobi** [comment]
I can't translate to Dutch because I am not a translator for Dutch language, but if you are a Dutch translator you should be able to edit Dutch translations.
This applies for all translations:
> Our translation service is at [translation.odoo-community.org](https://translation.odoo-community.org/).
>
>To start translating, please register there using your github login, and send an email to t[ransbot@odoo-community.org](mailto:transbot@odoo-community.org) saying which languages you want to translate to.

(from https://odoo-community.org/resources/translate)
If you are still having issues, I think you can write to transbot@odoo-community.org.

**Comment by pedrobaeza** [comment]
I don't know why it's blocked, but I have unblocked it.

**Comment by astirpe** [comment]
Thank you ! :+1:
