### ISSUE TITLE
[16.0]account_invoice_overdue_reminder: Partialy paid invoices not reminded

### ISSUE THREAD

**Issue by Yvesldff** [OCA/credit-control#330]
## Module
[16]account_invoice_overdue_reminder

## Describe the bug
It seems that, in v16, the account_invoice_overdue_reminder module does not take partially paid invoices into account in reminder.
If a customer has an invoice that has only been partially paid, it indicates that there is no reminder to be done for this customer.
This works well in v14 not in v16.

**Comment by ThijsvOers** [comment]
As an extra remark to this bug I wanted to share the following testresult: 

When you do a partial payment on an overdue reminder, all information regarding the sent payment reminder is gone (the tab 'overdue reminder'is invisible after doing the partial payment). I think this should not be happening, the rest of the payment that is still open should still be visible (since it's overdue).

**Comment by legalsylvain** [comment]
@alexis-via : could you take a look on this one ?
