### ISSUE TITLE
[12.0] sale.order in done (lock) state

### ISSUE THREAD

**Issue by rafamarpe** [OCA/credit-control#74]
Hi,
Is it possible to make this modification?.
I think that modifying these lines could be solved.

- sale_financial_risk/models/sale.py (line 72)
> def _compute_risk_amount(self):
>         for line in self:
>             **if line.state not in ('sale', 'done') and (
>                 line.invoice_status != 'invoiced'):**
>                 line.risk_amount = 0.0
>                 continue

- sale_financial_risk/models/res_partner.py (line 24)
> return self._get_risk_company_domain() + [
>             **('state', 'in', ('sale', 'done'))**,
>             ('commercial_partner_id', 'in', commercial_partners.ids),
>         ]

In this way, a completed order would mean that your invoice status was invoiced

Thanks!

**Comment by carlosdauden** [comment]
This is precisely done so that the user has a mechanism that excludes from the risk orders that have not been fully served and will no longer be served.
The invoiced state cannot be applied if 10 units are ordered, 1 is served and invoice is already in that state.

If you consider it appropriate, you can do a PR by adding a configuration option to determine if orders are included in the done state.

**Comment by rafamarpe** [comment]
If we add an option when automatic order blocking is chosen, which indicates whether to take these orders into account at risk?

**Comment by carlosdauden** [comment]
I prefer that you extract this condition to one function and you add option at company level or system parameter:
https://github.com/OCA/credit-control/blob/12.0/sale_financial_risk/models/sale.py#L73

After this, if you need aditional flow, you can extend that funcion in other module or customer extension.

**Comment by carlosdauden** [comment]
Fixed in https://github.com/OCA/credit-control/pull/78
