### ISSUE TITLE
[RFC][12.0] enhancement of sale_financial_risk

### ISSUE THREAD

**Issue by tafaRU** [OCA/credit-control#82]
I'd like to propose a little enhancement related to the `sale_financial_risk` module.
It basically consists in adding:

- a new state called `Risk Exceeded` to the sale order
- a button called `Bypass Risk`, only visibile in state `Risk Exceeded`, to confirm the sale order

WDYT?

**Comment by pedrobaeza** [comment]
There shouldn't be a new state, or that will break flows that expect the standard states. I know you are thinking in this way for simplifying the code, but for sure it will have secondary effects. You can add a boolean field that is filled when validating the order, aborting it, and hide standard validation button and showing the other (for allowed one), in that case.

Anyway, I want to hear @carlosdauden's opinion on this.

**Comment by tafaRU** [comment]
Thanks @pedrobaeza for your prompt feedback!

> You can add a boolean field that is filled when validating the order, aborting it, and hide standard validation button and showing the other (for allowed one), in that case.

This solution seems to me acceptable.
I remain awating opinion from @carlosdauden before proceeding.

**Comment by carlosdauden** [comment]
What is the goal of that new state/field?
Could it be looking for orders with that state/field to force confirmation in batch? Could it be done using the existing wizard instead of a new button?
Remember that risk state is something quite variable that depends on several things.
Perhaps seeing the implementation will make it clearer, I am not opposed to any kind of improvement as long as it does not affect performance

**Comment by pedrobaeza** [comment]
Also an integration with `sale_tier_validation` can be interesting instead of developing something apart, but indeed it's important the time factor: something that is in risk in one moment (or the contrary) can change in other moment of time.

**Comment by tafaRU** [comment]
@carlosdauden
> Could it be looking for orders with that state/field to force confirmation in batch?

Yes, this is the main reason. One of our customers would want to extrapolate the list of sale orders that have risk exceeded and decide which ones can be possibly confirmed.

> Perhaps seeing the implementation will make it clearer, I am not opposed to any kind of improvement as long as it does not affect performance

Ok, I propose the PR in order to evaluate it.

**Comment by tafaRU** [comment]
> There shouldn't be a new state, or that will break flows that expect the standard states. I know you are thinking in this way for simplifying the code, but for sure it will have secondary effects.

@pedrobaeza could you please give an example?

**Comment by pedrobaeza** [comment]
Right now I don't have an specific example, but I remember having this problem when adding a new state in sale.order in the past:

- Buttons visibility broken as some states are not included.
- Some code broken due to the same reason.

You will have side effects sooner or later, so it's not advisable IMO.

**Comment by tafaRU** [comment]
In the end I decided to go for a customization.
Well, thank you for your time.
